name: TWRP Recovery Builder 2024 Modificado

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Baixar e Compilar TWRP
      uses: kinguser981/TWRP-Recovery-Builder-2024@main
      with:
        MANIFEST_BRANCH: 'twrp-9.0'
        DEVICE_TREE_URL: 'https://github.com'
        DEVICE_TREE_BRANCH: 'main'
        DEVICE_PATH: 'device/multilaser/ML-SO06-M7sLite'
        DEVICE_NAME: 'ML-SO06-M7sLite'
        MAKEFILE_NAME: 'omni_ML-SO06-M7sLite'
        BUILD_TARGET: 'bootimage'
        PATH_OF_BLOBS: 'system/bin/sh'

